apiVersion: kubeconfig.stuttgart-things.com/v1alpha1
kind: RemoteCluster
metadata:
  name: test-cluster
spec:
  forProvider:
    source:
      path: examples/testdata/kubeconfig.yaml
    secretNamespace: crossplane-system
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
