apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: kubeconfig.stuttgart-things.com/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  git:
    url: https://github.com/stuttgart-things/xplane-provider-kubeconfig.git
    branch: main
  decryption:
    provider: sops
    secretRef:
      name: age-key
      namespace: crossplane-system
